import Head from "next/head";
import { useEffect, useState } from "react";
import { ConnectButton } from "thirdweb/react";
import type { FC } from "react";
import { Buy } from "~/components/Buy";
import { Sell } from "~/components/Sell";
import Sparkline from "~/components/Sparkline";
import AnimatedNumber from "~/components/AnimatedNumber";
import { client } from "~/constants";
import { api } from "~/utils/api";
import { Position } from "~/components/Position";

const Home: FC = () => {
  const [price, setPrice] = useState<number>(45000);
  const { data } = api.coingecko.getTokenCardDataById.useQuery({
    id: "coinbase-wrapped-btc",
  });
  useEffect(() => {
    if (!data)  return;
    setPrice(data.current_price);
  }, [data, data?.current_price]);

  const [activeAction, setActiveAction] = useState<"buy" | "sell" | undefined>();
  
  return (
    <>
      <Head>
        <title>Buy Bitcoin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <ConnectButton 
          client={client} 
          theme="light"
          connectModal={{
            showThirdwebBranding: false,
          }}
        />
        {data && (
          <div className="absolute w-full h-full -z-10 opacity-40">
            <Sparkline data={data.sparkline_in_7d.price} />
          </div>
        )}
        <div className="container flex flex-col items-center justify-center gap-2 px-4 py-16">
          <div className="text-7xl tracking-tighter font-bold">Buy Bitcoin</div>
          <div className="flex items-center gap-2 mb-8">
            <div className="text-4xl font-bold">
              {data && (
                <AnimatedNumber
                  value={price}
                  formatOptions={{
                    style: "currency",
                    currency: "usd",
                    maximumFractionDigits: 0,
                  }}
                />
              )}
            </div>
          </div>
          {!activeAction && (
            <div className="flex justify-center w-full max-w-md items-center gap-2">
              <button 
                className="btn btn-lg w-1/2 btn-primary"
                onClick={() => setActiveAction("buy")}
              >
                Buy
              </button>
              <button 
                className="btn btn-lg w-1/2 btn-secondary"
                onClick={() => setActiveAction("sell")}
              >
                Sell
              </button>
            </div>
          )}
          {activeAction === "buy" && (
            <Buy goBack={() => setActiveAction(undefined)} />
          )}
          {activeAction === "sell" && (
            <Sell goBack={() => setActiveAction(undefined)} />
          )}
          <Position />
        </div>
      </main>
    </>
  );
};

export default Home;
